# permissions for end users to edit environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: environment-editor-role
rules:
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - environments/status
  verbs:
  - get
