# permissions for end users to edit insightsbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insightsbase-editor-role
rules:
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - insightsbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - insightsbases/status
  verbs:
  - get
