# permissions for end users to view insightsbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insightsbase-viewer-role
rules:
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - insightsbases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - insightsbases/status
  verbs:
  - get
