# permissions for end users to view insightsapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insightsapp-viewer-role
rules:
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - insightsapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.redhat.com.cloud.redhat.com
  resources:
  - insightsapps/status
  verbs:
  - get
