# permissions for end users to edit jobinvocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobinvocation-editor-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - jobinvocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - jobinvocations/status
  verbs:
  - get
