
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - insightsapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - insightsapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.redhat.com
  resources:
  - insightsbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - insightsbases/status
  verbs:
  - get
  - patch
  - update
