apiVersion: v1
kind: Template
metadata:
  name: clowder-olm-bundle
parameters:
- name: IMAGE_TAG
  value: latest
- name: IMAGE
  value: quay.io/cloudservices/clowder-index
- name: TARGET_NAMESPACE
  value: clowder
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: clowder-source
  spec:
    sourceType: grpc
    image: ${IMAGE}:${IMAGE_TAG}
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: clowder
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: clowder
  spec:
    channel: alpha
    name: clowder
    source: clowder-source
    sourceNamespace: ${TARGET_NAMESPACE}
