apiVersion: v1
kind: Template
metadata:
  name: clowder-olm-bundle
parameters:
- name: VERSION
  value: 0.0.4
- name: TARGET_NAMESPACE
  value: clowder-system
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: clowder-source
  spec:
    sourceType: grpc
    image: quay.io/cloudservices/clowder-index:${VERSION}
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: clowder
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: clowder
  spec:
    channel: alpha
    name: clowder
    source: clowder-source
    sourceNamespace: ${TARGET_NAMESPACE}
